
go.property("game_speed", 230)



is_running = true


local function handle_game_over(self)
	is_running = false
end

function init(self)
		
	-- Set the game speed 
	go.set("scene/scene#script", "speed", self.game_speed)
	go.set("obstacle_spawner#script", "speed", self.game_speed)
end 

function update(self, dt)

end

function on_message(self, message_id, message, sender)
	if message_id == hash("game_over") then
		handle_game_over(self)
	end
end
