-- 1
go.property("speed", 230)

function init(self)
	msg.post("obstacle_spawner#script", "obstacle_created")
end

function remove_obstacle()
	go.delete()
	msg.post("obstacle_spawner#script", "obstacle_deleted") 
end 

function update(self, dt)
	if is_running == false then
		return
	end
	
	-- 2
	local p = go.get_position()
	p.x = p.x - self.speed * dt

	-- 3
	if p.x < -100 then		
		remove_obstacle()
		return;
	end

	-- 4
	go.set_position(p)

end